[package]
name = "rust"
version = "0.1.0"
authors = ["Philser <pk30.05@hotmail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.7.0"